import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { NavBarButtons } from "../components/navbar"; // Adjust the path as necessary

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <header>
            <nav>
              <NavBarButtons />
            </nav>
          </header>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
